import React from "react";
import TextInputField from "../../../components/common/TextInputField";

const Merchantcommissionplan = ({isEditable}) => {
  return (
    <div className="bg-[#1E252B] p-6 rounded-lg w-full mb-[15px]">
      <div className="grid grid-cols-1 sm:grid-cols-3 gap-[25px]">
        <TextInputField
          rightTextValue="USD"
          type="text"
          placeholder=""
          label="From"
          name="from"
          value="100"
          readOnly={!isEditable}
          bgColor={"#283641"}
        />
        <TextInputField
          rightTextValue="USD"
          type="text"
          placeholder=""
          label="To"
          name="to"
          value="100"
          readOnly={!isEditable}
          bgColor={"#283641"}
        />
        <TextInputField
          rightTextValue="%"
          type="text"
          placeholder=""
          label="Commission"
          name="commission"
          value="14"
          readOnly={!isEditable}
          bgColor={"#283641"}
        />
        <TextInputField
          rightTextValue="USD"
          type="text"
          placeholder=""
          label="From"
          name="from"
          value="100"
          readOnly={!isEditable}
          bgColor={"#283641"}
        />
        <TextInputField
          rightTextValue="USD"
          type="text"
          placeholder=""
          label="To"
          name="to"
          value="100"
          readOnly={!isEditable}
          bgColor={"#283641"}
        />
        <TextInputField
          rightTextValue="%"
          type="text"
          placeholder=""
          label="Commission"
          name="commission"
          value="14"
          readOnly={!isEditable}
          bgColor={"#283641"}
        />
        <TextInputField
          rightTextValue="USD"
          type="text"
          placeholder=""
          label="From"
          name="from"
          value="100"
          readOnly={!isEditable}
          bgColor={"#283641"}
        />
        <TextInputField
          rightTextValue="USD"
          type="text"
          placeholder=""
          label="To"
          name="to"
          value="100"
          readOnly={!isEditable}
          bgColor={"#283641"}
        />
        <TextInputField
          rightTextValue="%"
          type="text"
          placeholder=""
          label="Commission"
          name="commission"
          value="14"
          readOnly={!isEditable}
          bgColor={"#283641"}
        />
        <TextInputField
          rightTextValue="USD"
          type="text"
          placeholder=""
          label="From"
          name="from"
          value="100"
          readOnly={!isEditable}
          bgColor={"#283641"}
        />
        <TextInputField
          rightTextValue="USD"
          type="text"
          placeholder=""
          label="To"
          name="to"
          value="100"
          readOnly={!isEditable}
          bgColor={"#283641"}
        />
        <TextInputField
          rightTextValue="%"
          type="text"
          placeholder=""
          label="Commission"
          name="commission"
          value="14"
          readOnly={!isEditable}
          bgColor={"#283641"}
        />
        <TextInputField
          rightTextValue="USD"
          type="text"
          placeholder=""
          label="From"
          name="from"
          value="100"
          readOnly={!isEditable}
          bgColor={"#283641"}
        />
        <TextInputField
          rightTextValue="USD"
          type="text"
          placeholder=""
          label="To"
          name="to"
          value="100"
          readOnly={!isEditable}
          bgColor={"#283641"}
        />
        <TextInputField
          rightTextValue="%"
          type="text"
          placeholder=""
          label="Commission"
          name="commission"
          value="14"
          readOnly={!isEditable}
          bgColor={"#283641"}
        />
        <TextInputField
          rightTextValue="USD"
          type="text"
          placeholder=""
          label="From"
          name="from"
          value="100"
          readOnly={!isEditable}
          bgColor={"#283641"}
        />
        <TextInputField
          rightTextValue="USD"
          type="text"
          placeholder=""
          label="To"
          name="to"
          value="100"
          readOnly={!isEditable}
          bgColor={"#283641"}
        />
        <TextInputField
          rightTextValue="%"
          type="text"
          placeholder=""
          label="Commission"
          name="commission"
          value="14"
          readOnly={!isEditable}
          bgColor={"#283641"}
        />
        <TextInputField
          rightTextValue="USD"
          type="text"
          placeholder=""
          label="From"
          name="from"
          value="100"
          readOnly={!isEditable}
          bgColor={"#283641"}
        />
        <div></div>
        <TextInputField
          rightTextValue="%"
          type="text"
          placeholder=""
          label="Commission"
          name="commission"
          value="14"
          readOnly={!isEditable}
          bgColor={"#283641"}
        />

        <div className="space-y-6 text-white">
          <div className="flex items-center justify-between w-full">
            <span className="text-sm font-medium">
              Seller profit sharing when 'Be partner with Estipal' is selected
            </span>
            <div className="flex items-center space-x-2">
              <input
                type="text"
                value={"50"}
                className="w-[70px] flex items-center justify-center text-center px-2 py-1 bg-gray-700 text-[#FFA13C] rounded border border-gray-600 focus:outline-none focus:ring focus:ring-[#3c8dbc]"
              />
              <span>{"%"}</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Merchantcommissionplan;
